- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: pretty-format-json
      args:
        - '--autofix'
        - '--no-sort-keys'
    - id: trailing-whitespace
