" ### key mapping
" remap leader key
let mapleader = ","
" go to the next buffer
nmap <leader>l :bnext<cr>

" go to the previous buffer
nmap <leader>h :bprevious<cr>

" close buffer
nmap <leader>bq :bp <bar> bd #<cr>
" ### end key mapping

" syntax highlighting
syntax on

" indentation options
set tabstop=4
set expandtab
set shiftwidth=4
set autoindent
set smartindent

" show whitespace characters
set list listchars=tab:»─,trail:•,nbsp:⍽

" view line number
set number

" Relative line numbering
set relativenumber

" Use visual bell instead of beeping
set visualbell

" Split below, more natural
set splitbelow

" Split right, more natural
set splitright

" Highlight current line
set cursorline

" Show at least 4 lines above/below the cursor
set scrolloff=4

" 256 colors terminal
set t_Co=256

filetype plugin indent on

" pathogen VIM plugin manager
runtime bundle/pathogen.vim/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()

" force shell because vim doesn't seem to work well with fishshell
set shell=/bin/sh

" ctrlp.vim fuzzyfinder plugin
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_show_hidden = 1

" Ctrl+n to toggle to open/close NERDTree
map <C-n> :NERDTreeToggle<CR>

" molokai colorscheme
colorscheme molokai

" vim-airline
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
let g:airline#extensions#tabline#enabled = 1

" tmuxline.vim
" To see the updates, run ':w | :source ~/.vimrc | Tmuxline'.
" Once finished, run ':TmuxlineSnapshot! ~/.tmuxline.vim.conf' to save the
" changes.
let g:tmuxline_theme = 'powerline'
let g:tmuxline_preset = {
        \'a'    : ['#H', '#(whoami)'],
        \'b'    : '',
        \'c'    : '',
        \'win'  : ['#I', '#W'],
        \'cwin' : ['#I', '#W', '#F'],
        \'x'    : '',
        \'y'    : '#(uptime | sed "s/.*load average: //")',
        \'z'    : '%R'}
" do not let Airline override Tmuxline conf
let g:airline#extensions#tmuxline#enabled = 0

" promptline.vim
" To see the updates, run ':w | source ~/.vimrc | PromptlineSnapshot! ~/.shell_prompt.sh' in vim, then run 'source ~/.config/fish/shell_prompt.sh' in a bash prompt, or 'source .config/fish/config.fish' in a fish prompt
let g:promptline_theme = 'powerlineclone'
"let g:promptline_preset = 'full'
"unlet g:promptline_preset
let g:promptline_preset = {
        \'a'    : [ promptline#slices#host(), promptline#slices#user() ],
        \'b'    : [ promptline#slices#cwd() ],
        \'c'    : [ ],
        \'x'    : [ promptline#slices#git_status(), promptline#slices#vcs_branch() ],
        \'y'    : [ '$(date "+%H:%M:%S")' ],
        \'z'    : [ ],
        \'warn' : [ promptline#slices#last_exit_code() ]}

if filereadable(glob("~/.vimrc_local"))
    source ~/.vimrc_local
endif

